### ISSUE TITLE
jsreport studio upload image breaks everything

### ISSUE THREAD

**Issue by Jonlee2001** [jsreport/jsreport-express#2] opened 2016-01-07 17:58 UTC
When I upload an image using the "images" tab in jsreport studio the logs say "Uploading done" but the image itself is not displayed in the editor. I then refreshed the page to get to to load and the whole application hangs waiting for a call to:
https://localhost/js/require_main.js?studio=normal&bust=1450185024358&studio=normal
I can no longer access any part of the application as it hangs on the call to the above on every page.
Restarting the application doesn't help, stopping the app and deleted the image from the images folder doesn't help either.
This has happened on my local (windows) copy but also on my docker image copy.
The image itself is my company logo in PNG format (350px x 150px ~ 14kb in size).

**Comment by pofider** [comment] 2016-01-08 08:22
Thank you for submitting issue. Unfortunately I am not able to reproduce this. Tested on the latest 0.11 with production as well as development environment. I did also test both nedb as well as newer fs store.

Please report which version of jsreport you have. It could have been fixed in the past releases, there were some fixes for images. And also please let us know what kind of store you use (the connectionString.name value)

**Closed as completed** 2016-04-19 16:00 UTC
